### ISSUE TITLE
The library doesn't work with Groovy 4

### ISSUE THREAD

**Issue by dstepanov** [kayr/fuzzy-csv#2]
I'm trying to use `io.github.kayr:fuzzy-csv:1.8.1-groovy4`, but I'm getting an exception:

```
Caused by: java.lang.NoSuchMethodError: 'java.util.List org.codehaus.groovy.runtime.ScriptBytecodeAdapter.createRange(java.lang.Object, java.lang.Object, boolean, boolean)'
        at fuzzycsv.FuzzyCSV.mergeByAppending(FuzzyCSV.groovy:798)
        at fuzzycsv.FuzzyCSV$mergeByAppending$8.callStatic(Unknown Source)
        at fuzzycsv.FuzzyCSV.mergeByColumn(FuzzyCSV.groovy:746)
        at fuzzycsv.FuzzyCSV$mergeByColumn$5.call(Unknown Source)
```

It looks like some of the classes need to migrate to `org.apache.groovy`.

**Comment by kayr** [comment]
Oh.. no.. thanks for reporting this. Let me check this later on.

**Comment by kayr** [comment]
@dstepanov 
I am trying to reproduce your error using the code below. But unfortunately unable to reproduce it yet.. this is my gradle file
```
plugins {
    id 'groovy'
}


repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.groovy:groovy-all:4.0.7'
    implementation 'io.github.kayr:fuzzy-csv:1.8.1-groovy4'
}
```

And this is the code..
```
import fuzzycsv.FuzzyCSVTable

def csv = [
        ['one', 'two', 'three'],
        ['1', '2', '3'],
        ['4', '5', '6'],
        ['7', '8', '9']]
def csv2 = [
        ['one', 'two', 'three'],
        ['10', '20', '30'],
        ['40', '50', '60'],
        ['70', '80', '90']]


FuzzyCSVTable
        .tbl(csv)
        .mergeByColumn(csv2)
        .printTable()
```
Output
```
╔═════╤═════╤═══════╗
║ one │ two │ three ║
╠═════╪═════╪═══════╣
║ 1   │ 2   │ 3     ║
╟─────┼─────┼───────╢
║ 4   │ 5   │ 6     ║
╟─────┼─────┼───────╢
║ 7   │ 8   │ 9     ║
╟─────┼─────┼───────╢
║ 10  │ 20  │ 30    ║
╟─────┼─────┼───────╢
║ 40  │ 50  │ 60    ║
╟─────┼─────┼───────╢
║ 70  │ 80  │ 90    ║
╚═════╧═════╧═══════╝
```
Could you probably share your groovy version and java version. Or may be the code snippet reproducing this error...

**Comment by kayr** [comment]
@dstepanov 
I had a second look at this and I think I have found the problem. It seems to be related to a conflict between groovy versions as you already mentioned.

The new method seems to have been introduced in this commit
https://github.com/apache/groovy/commit/75b71337571bcf3517aec7b3a89b3603fac1d329 and I think code compiled with newer groovy versions references this method, while code compiled with older groovy versions references the old method.

Am not sure which groovy version you are using in your classpath but I would suggest you probably try `io.github.kayr:fuzzy-csv:1.8.1-groovy3` which is compatible with lower groovy versions

From my quick investigation the gradle dependency section below reproduced the error:
```
// this reproduces the error   (groovy4 variant + groovy 3.0.8)
dependencies {
    implementation 'io.github.kayr:fuzzy-csv:1.8.1-groovy4', {
        exclude group:'org.apache.groovy', module:'groovy-sql'
        exclude group:'org.apache.groovy', module:'groovy-json'
        exclude group:'org.apache.groovy', module:'groovy-bom'
        exclude group:'org.apache.groovy', module:'groovy'
    }

    implementation 'org.codehaus.groovy:groovy-all:3.0.8'
}
``` 

And the following variants all worked
```
//this works (groovy4 variant + groovy 4.0.7)
dependencies {
    implementation 'io.github.kayr:fuzzy-csv:1.8.1-groovy4', {
        exclude group:'org.apache.groovy', module:'groovy-sql'
        exclude group:'org.apache.groovy', module:'groovy-json'
        exclude group:'org.apache.groovy', module:'groovy-bom'
        exclude group:'org.apache.groovy', module:'groovy'
    }

    implementation 'org.apache.groovy:groovy-all:4.0.7'
}
```
```
//this works (groovy3 variant + groovy 3.0.8)
dependencies {
    implementation 'io.github.kayr:fuzzy-csv:1.8.1-groovy3'
    implementation 'org.codehaus.groovy:groovy-all:3.0.8'
}
```

```
//this works (groovy3 variant + groovy 2.5.3)
dependencies {
    implementation 'io.github.kayr:fuzzy-csv:1.8.1-groovy3'
    implementation 'org.codehaus.groovy:groovy-all:2.5.3'
}
```

**Comment by dstepanov** [comment]
I'm using it here https://github.com/dstepanov/micronaut-jhm-benchmarks/blob/main/buildSrc/src/main/groovy/io.micronaut.internal.jmh.merge.gradle

You can reproduce it by using the default Gradle's Groovy and `.1.8.1-groovy4` version https://github.com/dstepanov/micronaut-jhm-benchmarks/blob/main/buildSrc/build.gradle

**Comment by kayr** [comment]
Thanks for the reference.. I downloaded the code and verified that the version internally used by gradle is `3.0.13` which is not compatible with `.1.8.1-groovy4` hence the reason only `.1.8.1-groovy3` works.


```
./gradlew -version                                                                                                                        

------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.2 (Azul Systems, Inc. 17.0.2+8-LTS)
OS:           Linux 6.1.1-1-MANJARO amd64
```

 I guess in future I should add better error handling at runtime to show these incompatibilities. i.e  `*-groovy4` variants are only compatible with `groovy4`  while `*-groovy3` variants are compatible with `groovy3` and below.
